---
- name: Set variables
  ansible.builtin.set_fact:
    user_name: "{{ admin_user }}"

- name: Set up the repository
  become: true
  ansible.builtin.package:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: add docker's official GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: register dpkg architecture name
  shell: dpkg --print-architecture
  register: arch

- name: Set up docker apt repository
  become: true
  apt_repository:
    repo: "deb [arch={{ arch.stdout }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_version | default('stable')}}"
    state: present

- name: Update apt cache
  become: true
  apt:
    update_cache: true

- name: Install docker engine
  become: true
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Add user to docker group
  become: true
  user:
    name: "{{ user_name }}"
    groups: docker
    append: true
